# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 14:37
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidgeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codgeo', models.CharField(max_length=20)),
                ('idade', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=254)),
                ('continuacao', models.CharField(max_length=250)),
                ('cont_2', models.CharField(max_length=250)),
                ('cont_3', models.CharField(max_length=250)),
                ('era', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('cor', models.CharField(max_length=6)),
                ('legenda', models.CharField(max_length=8)),
                ('codgeo_ori', models.CharField(max_length=50)),
                ('newfield1', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
