# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('altitudemode', models.CharField(max_length=1024)),
                ('tessellate', models.IntegerField()),
                ('extrude', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('draworder', models.IntegerField()),
                ('icon', models.CharField(max_length=1024)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Unidgeo',
        ),
    ]
