# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0003_auto_20160513_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
